"""empty message

Revision ID: 92f7923725fc
Revises: dddaa474990c
Create Date: 2019-03-09 08:34:06.606362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92f7923725fc'
down_revision = 'dddaa474990c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.add_column('item', sa.Column('negara', sa.String(length=255), nullable=True))
    op.add_column('item', sa.Column('new_price', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('old_price', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('qty', sa.Integer(), nullable=True))
    op.drop_column('item', 'harga')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('harga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('item', 'qty')
    op.drop_column('item', 'old_price')
    op.drop_column('item', 'new_price')
    op.drop_column('item', 'negara')
    op.create_table('client',
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('confirm_password', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
