"""empty message

Revision ID: dddaa474990c
Revises: 
Create Date: 2019-03-06 09:24:46.700413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddaa474990c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('confirm_password', sa.String(length=20), nullable=True))
    op.add_column('client', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'email')
    op.drop_column('client', 'confirm_password')
    # ### end Alembic commands ###
